#!/usr/bin/env bash
# Bootstrap the local environment for the steering-vectors feature.
#
# What it does:
#   1. Verifies required tools (supabase, python3, node, npm).
#   2. Starts the Supabase stack if not already running.
#   3. Reads `supabase status --output env` to get project-specific keys.
#   4. Generates a fresh INTERP_INTERNAL_SECRET (32 hex chars).
#   5. Writes .env for red-hacks-frontend/ and interp-backend/.
#   6. Installs Python deps into a venv at interp-backend/.venv.
#   7. Installs Node deps via npm ci if node_modules is missing.
#
# Safe to re-run: existing .env files are backed up to .env.bak.<timestamp>.
#
# Usage (from red-hacks-frontend/):
#   bash scripts/setup-local-steering.sh
#
# After it finishes, follow the printed "Next steps" to start each service.

set -euo pipefail

FRONTEND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="${FRONTEND_DIR}/interp-backend"
TIMESTAMP="$(date +%Y%m%d%H%M%S)"

note()  { printf "\033[36m[setup]\033[0m %s\n" "$*"; }
warn()  { printf "\033[33m[warn]\033[0m  %s\n" "$*"; }
fail()  { printf "\033[31m[fail]\033[0m  %s\n" "$*" >&2; exit 1; }

# -----------------------------------------------------------------------------
# 1. Tool check
# -----------------------------------------------------------------------------
note "Checking required tools…"
for tool in supabase python3 node npm; do
	if ! command -v "${tool}" >/dev/null 2>&1; then
		fail "${tool} not found on PATH. Install it and re-run."
	fi
done
note "  supabase: $(supabase --version)"
note "  python3:  $(python3 --version)"
note "  node:     $(node --version)"
note "  npm:      $(npm --version)"

# -----------------------------------------------------------------------------
# 2. Start Supabase if stopped
# -----------------------------------------------------------------------------
cd "${FRONTEND_DIR}"

# The Supabase CLI auto-reads .env from cwd. If a prior run wrote a
# malformed .env, every supabase subcommand will fail until we move it
# aside — do that before any CLI call so the bootstrap is always able
# to recover itself.
quarantine_broken_env() {
	local target="$1"
	[[ -f "${target}" ]] || return 0
	if ! supabase --workdir "${FRONTEND_DIR}" status >/dev/null 2>&1; then
		local reason
		reason="$(supabase --workdir "${FRONTEND_DIR}" status 2>&1 || true)"
		if grep -q 'failed to parse environment file' <<<"${reason}"; then
			mv "${target}" "${target}.broken.${TIMESTAMP}"
			warn "Quarantined malformed ${target} → ${target}.broken.${TIMESTAMP}"
		fi
	fi
}
quarantine_broken_env "${FRONTEND_DIR}/.env"

if supabase status >/dev/null 2>&1; then
	note "Supabase is already running."
else
	note "Starting Supabase (this takes ~30s the first time)…"
	supabase start
fi

# -----------------------------------------------------------------------------
# 3. Pull project-specific keys
# -----------------------------------------------------------------------------
note "Reading Supabase keys…"
# `supabase status --output env` emits shell-parseable KEY="value" lines.
# Using `set -a; eval …; set +a` so each assignment is auto-exported,
# without the quoting fragility of `export $(…)`.
STATUS_ENV="$(supabase status --output env)"
set -a
# shellcheck disable=SC2294
eval "${STATUS_ENV}"
set +a
# Variables provided by Supabase: API_URL, ANON_KEY, SERVICE_ROLE_KEY, …
: "${API_URL:?supabase status did not expose API_URL}"
: "${ANON_KEY:?supabase status did not expose ANON_KEY}"
: "${SERVICE_ROLE_KEY:?supabase status did not expose SERVICE_ROLE_KEY}"

# -----------------------------------------------------------------------------
# 4. Generate INTERP_INTERNAL_SECRET
# -----------------------------------------------------------------------------
INTERP_SECRET="$(python3 -c 'import secrets;print(secrets.token_hex(32))')"

# -----------------------------------------------------------------------------
# 5. Write .env files
# -----------------------------------------------------------------------------
write_env() {
	local target="$1" contents="$2"
	if [[ -f "${target}" ]]; then
		cp "${target}" "${target}.bak.${TIMESTAMP}"
		note "Backed up existing $(basename "${target}") → $(basename "${target}").bak.${TIMESTAMP}"
	fi
	printf "%s" "${contents}" > "${target}"
	chmod 600 "${target}"
	note "Wrote ${target}"
}

FRONTEND_ENV=$(cat <<EOF
# Generated by scripts/setup-local-steering.sh at ${TIMESTAMP}
PUBLIC_SUPABASE_URL=${API_URL}
PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
PUBLIC_MAX_UPLOAD_MB=10
MAX_UPLOAD_MB=10

# Used by src/routes/api/steering-vectors/+server.ts to reach the interp
# backend. Must match the value in interp-backend/.env.
INTERP_BACKEND_URL=http://127.0.0.1:8000
INTERP_INTERNAL_SECRET=${INTERP_SECRET}
EOF
)

BACKEND_ENV=$(cat <<EOF
# Generated by scripts/setup-local-steering.sh at ${TIMESTAMP}
STEER_MODEL_NAME=gpt2
PORT=8000
SUPABASE_URL=${API_URL}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
INTERP_INTERNAL_SECRET=${INTERP_SECRET}
ENABLE_USER_STEERING_VECTORS=true
EOF
)

write_env "${FRONTEND_DIR}/.env" "${FRONTEND_ENV}"
write_env "${BACKEND_DIR}/.env" "${BACKEND_ENV}"

# -----------------------------------------------------------------------------
# 6. Python venv for the backend
# -----------------------------------------------------------------------------
if [[ ! -d "${BACKEND_DIR}/.venv" ]]; then
	note "Creating Python venv at interp-backend/.venv…"
	python3 -m venv "${BACKEND_DIR}/.venv"
fi
note "Installing Python deps (this is heavy — torch + transformers)…"
# shellcheck disable=SC1091
source "${BACKEND_DIR}/.venv/bin/activate"
pip install --quiet --upgrade pip
pip install --quiet -r "${BACKEND_DIR}/requirements.txt"
deactivate

# -----------------------------------------------------------------------------
# 7. Node deps
# -----------------------------------------------------------------------------
if [[ ! -d "${FRONTEND_DIR}/node_modules" || ! -f "${FRONTEND_DIR}/node_modules/.package-lock.json" ]]; then
	note "Installing Node deps…"
	(cd "${FRONTEND_DIR}" && npm ci)
else
	note "node_modules already populated — skipping npm ci."
fi

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------
cat <<EOF

\033[32m[ok]\033[0m    Setup complete.

Next steps — run each in its own terminal:

  Terminal 1 — interp-backend (loads gpt2 on boot, ~30s):
    cd ${BACKEND_DIR}
    source .venv/bin/activate
    uvicorn steering_backend:app --reload --port 8000

  Terminal 2 — SvelteKit dev server:
    cd ${FRONTEND_DIR}
    npm run dev

Then visit http://localhost:5173 (or whatever Vite prints).

Useful URLs while you're testing:
  Frontend         http://localhost:5173
  Supabase Studio  http://127.0.0.1:54323   (SQL editor + row viewer)
  Inbucket (mail)  http://127.0.0.1:54324   (signup confirmation emails)
  Backend health   http://127.0.0.1:8000/health
  Backend model    http://127.0.0.1:8000/v1/model-info
EOF
